name: issue

on: 
  issues:
    types: opened

env:
  IC: "issue Created"
  
jobs:
  message:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: le message

        run: echo "$IC"

